import mongoose from "mongoose";

const fabricSchema=new mongoose.Schema({
    DOC_NO:{
            type:String,
            required:true,
            trim:true
    },
    DATE:{
            type:String,
            required:true,
            trim:true
    },
    JOB_ORDER_NO:{
            type:String,
            required:true,
            trim:true
    },
    RECORD_TYPE:{
            type:String,
            required:true,
            trim:true
    },
    FABRIC_GROUP:{
            type:String,
            required:true,
            trim:true
    },
    COLOR_NAME:{
            type:String,
            required:true,
            trim:true
    },
    SET_NO:{
            type:String,
            required:true,
            trim:true
    },
    DC_DIA:{
            type:String,
            required:true,
            trim:true
    },
    DIA_TYPE:{
            type:String,
            required:true,
            trim:true
    },
  PRCESS_NAME:{
            type:String,
            required:true,
            trim:true
    },
  PROCESS_DC_NO:{
            type:String,
            required:true,
            trim:true
    },
  COMPACT_NO:{
            type:String,
            required:true,
            trim:true
    },
  RECD_DC_NO:{
            type:String,
            required:true,
            trim:true
    },
  RECD_DC_DATE:{
            type:String,
            required:true,
            trim:true
    },
  RECD_DC_ROLL:{
            type:String,
            required:true,
            trim:true
    },
  RECD_DC_WGT:{
            type:String,
            required:true,
            trim:true
    }
})

const Fabric=mongoose.model('fabric',fabricSchema)

export default Fabric